[build]
  # This command installs Flutter, then builds the web app
  command = "curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.2-stable.tar.xz | tar xJ && export PATH=\"$PWD/flutter/bin:$PATH\" && flutter doctor && flutter build web --release"
  publish = "build/web" # The directory where Flutter web output is placed

# Crucial for Flutter's client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true