[build]
  # This command installs Flutter (with a compatible Dart SDK), then builds the web app
  command = "curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.5-stable.tar.xz | tar xJ && export PATH=\"$PWD/flutter/bin:$PATH\" && flutter doctor && flutter build web --release"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true